server:
   port: 9002
spring:
  datasource:
    password: afsaralam15
    url: jdbc:mysql://genx.ccbfstqie49d.ap-south-1.rds.amazonaws.com:3306/user?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
      name: user-service
      
  zipkin:
     base-url: http://localhost:9411/
     

eureka:
   instance:
      preferIpAddress: true
      hostname: eureka-0
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka    