server:
  port: 9001
spring:
  datasource:
    password: afsaralam15
    url: jdbc:mysql://localhost:3306/department?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  application:
      name: department-service
     
  zipkin:
     base-url: http://localhost:9411/
